name: Build on DockerHub and Deploy to AWS
on:
  push:
    branches:
      - qubitsfrontend
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
  QBFRONT_HOST_DNS: ${{ secrets.QBFRONT_HOST_DNS }}
  QBFRONT_USERNAME: ${{ secrets.QBFRONT_USERNAME }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          Dockerfile: ./Dockerfile
          tags: karthickmuppilirajan/qbfrontend:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      # - name: Set permissions for private key
      #   run: |
      #     echo "${{ secrets.AWS_PRIVATE_KEY }}" | base64 -d > key.pem
      #     chmod 600 key.pem
      - name: SSH into EC2 and Run Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.QBFRONT_HOST_DNS }}
          username: ${{ secrets.QBFRONT_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }} 
          script: |
            sudo docker pull karthimuppilirajan/qbfrontend:latest
            sudo docker stop qbfrontend
            sudo docker rm qbfrontend
            sudo docker run -d --name qbfrontend -p 80:3000 karthickmuppilirajan/qbfrontend:latest